sonar.projectKey=python-basic-project 
sonar.projectName="Python Basic Project" 
sonar.projectVersion=1.0 
sonar.sources=. 
sonar.sourceEncoding=UTF-8 
sonar.host.url=http://40.82.169.72:9000 
sonar.token=sqp_84340a51a5892c740abf2d739ef10c4cb6ed05b2
  
